# Generated by Django 2.1.2 on 2019-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('message_timestamp', models.DateTimeField(auto_now=True, verbose_name='date messaged')),
            ],
        ),
    ]
