# Generated by Django 2.1.2 on 2019-05-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
